<?xml version="1.0" encoding="UTF-8"?>
<startNode name="&lt;start&gt;">
   <methodCall name="MethodCallOnObjectWithException.main();">
      <statement name="MethodCallOnObjectWithException x = new MethodCallOnObjectWithException ();">
         <statement name="return x.doSomething();">
            <methodCall name="x.doSomething();">
               <statement name="MethodCallOnObjectWithException x = null;">
                  <statement name="return x_3.return42();">
                     <branchCondition name="Normal Execution (x_3 != null)">
                        <methodCall name="x_3.return42();">
                           <statement name="return 42;">
                              <methodReturn name="&lt;return of x_3.return42();&gt;" nameIncludingReturnValue="&lt;return &apos;42&apos; as result of x_3.return42();&gt;">
                                 <methodReturn name="&lt;return of x.doSomething();&gt;" nameIncludingReturnValue="&lt;return &apos;42&apos; as result of x.doSomething();&gt;">
                                    <methodReturn name="&lt;return of MethodCallOnObjectWithException.main();&gt;" nameIncludingReturnValue="&lt;return &apos;42&apos; as result of MethodCallOnObjectWithException.main();&gt;">
                                       <termination name="&lt;end&gt;" exceptionalTermination="false">
                                       </termination>
                                    </methodReturn>
                                 </methodReturn>
                              </methodReturn>
                           </statement>
                        </methodCall>
                     </branchCondition>
                  </statement>
               </statement>
            </methodCall>
         </statement>
      </statement>
   </methodCall>
</startNode>
